image: alpine:latest

pages:
#  image: alpine-infosansordi
  script:
  - apk add --no-cache mdbook pipx texlive texmf-dist-langfrench texmf-dist-latexextra make
  - pipx install --global linkchecker
  - cd info-débranchée
  - make -C src/Nim
  - mdbook build
  - mkdir ../public; mv book/* ../public
  - linkchecker ../public
  artifacts:
    paths:
    - public

