TRACES= 
PREPS=  
MATOS=
RAPPORTS=$(patsubst Rapports/%.md,Rapports/%.html,$(wildcard Rapports/*.md))

IMG=materiel_magie-100x.jpg

TARGETS=${TRACES} ${MATOS} ${PREPS} ${RAPPORTS} ${IMG}

include ../Makefile.defs
